standards-update-11-3
whitebox-co/js-unit-testing-guide pull request #5
Opened 2021-11-03 16:36 UTC by aolszewski

2021-11-03 16:41 UTC, josh-fisher approved these changes

2021-11-04 15:06 UTC, nitzan-frock requested changes

2021-11-04 15:06 UTC, nitzan-frock commented on README.md
> +	const resposne = api.processOrders(order);
```suggestion
	const response = api.processOrders(order);

```

2021-11-04 15:06 UTC, nitzan-frock commented on README.md
> +	const resposne = api.processOrders(order);
```suggestion
	const response = api.processOrders(order);

```

2021-11-04 15:06 UTC, nitzan-frock commented on README.md
> +it('should process the order save it to the datbase and trigger the webhook', () => {
```suggestion
it('should process the order and save it to the database and trigger the webhook', () => {

```

2021-11-09 15:24 UTC, josh-fisher approved these changes

2021-11-09 15:26 UTC, merged